### ISSUE TITLE
react-ciscospark build failed on Windows

### ISSUE THREAD

**Issue by Rajakumar-vasel** [ciscospark/react-ciscospark#440]
Hi,
    Is Cygwin needed to build react-ciscospark from source. I got the following error 
   
E:\Raj\Vasel\CiscoSpark\GitHub\react-ciscospark\react-ciscospark>npm run build

> @ciscospark/react-ciscospark@0.1.161 build E:\Raj\Vasel\CiscoSpark\GitHub\react-ciscospark\react-ciscospark
> ./scripts/build/index.js

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "E:\\Raj\\Vasel\\WebRTC\\NodeJS\\node.exe" "E:\\Raj\\Vasel\\WebRTC\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ciscospark/react-ciscospark@0.1.161 build: `./scripts/build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ciscospark/react-ciscospark@0.1.161 build script './scripts/build/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ciscospark/react-ciscospark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/build/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ciscospark/react-ciscospark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ciscospark/react-ciscospark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Raj\Vasel\CiscoSpark\GitHub\react-ciscospark\react-ciscospark\npm-debug.log

The build process refers ./scripts/build/index.js that is intended for Linux Shell 
[npm-debug.zip](https://github.com/ciscospark/react-ciscospark/files/1245682/npm-debug.zip)

**Comment by adamweeks** [comment]
Hey, we are currently working on better build support for windows. You can keep an eye on this issue #353 for updates.
