### ISSUE TITLE
When using an @mention, the user list obstructs where a user enters text. When the user starts typing, you can see the text area again.

### ISSUE THREAD

**Issue by pdettorre-blz** [ciscospark/react-ciscospark#580]
Screenshot:

![sparkissue2](https://user-images.githubusercontent.com/28278555/33406374-6a56eb6e-d521-11e7-89f4-fee71989ea0e.png)

**Comment by adamweeks** [comment]
It appears this is resolved. @pdettorre-blz please let us know if it is not and the steps to reproduce.
