### ISSUE TITLE
media/UPDATE_REMOTE_MEDIA action is never called

### ISSUE THREAD

**Issue by cseale** [ciscospark/react-ciscospark#87]
When using the [demo](https://code.s4d.io/widget-message-meet/latest/demo/index.html) and monitoring the Redux State, I have noted the the UPDATE_REMOTE_MEDIA action is not called, and therefore the video stream from the user I am calling is never displayed.

**Comment by cseale** [comment]
This issue is related to https://github.com/ciscospark/spark-js-sdk/pull/493

**Comment by bzang** [comment]
@cseale, can you pul down the latest code and see if the issue has been resolved? We pushed out some updates to the sdk that should fix this issue.

**Comment by cseale** [comment]
@bzang yup can confirm this is resolved. Also experienced a strange issue where `localhost` was not being treated as secure in any browser I used. Don't know if it was related to any changes made to the SDK at any time or sounds familiar to you? 

Either ways I will close this particular issue.
